routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Models\Post;
use App\Models\User;
use App\Models\Category;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('posts.index'));
})->name('home');

// Route::get('/posts/{post:slug}', function (Post $post) {
//     return view('post', [
//         'post' => $post
//     ]);
// });



Route::get('categories/{category:slug}', function (Category $category) {
    return view('posts.index', [
        'posts' => $category->posts,
        'currentCategory' => $category,
        'categories' => Category::all()
    ]);
})->name('category');

Route::get('authors/{author:username}', function (User $author) {
    return view('posts.index', [
        'posts' => $author->posts,
        'categories' => Category::all()
    ]);
});

Route::resource('posts', PostController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Models/Logic/Posts.php
<?php

namespace App\Models\Logic;

class Posts
{
   public static function makeExcerpt($body, $length = 5){
    return substr($body, 0, $length);
   }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'body', 'slug', 'category_id', 'user_id', 'excerpt'];

    protected $with = ['category', 'author'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\post;
use App\Models\Category;
use App\Models\Logic\Posts;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->get();
        $categories = Category::all();
        return view('posts.index', compact('posts', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $storeData = $request->validate([
            'title' => 'required|max:255',
            'category_id' => 'required',
            'body' => 'required',
            'slug' => 'required|max:255',
            'user_id' => 'required'
        ]);
        $storeData['excerpt'] = Posts::makeExcerpt($storeData['body']);
        $post = Post::create($storeData);

        return redirect(route('posts.index'))->with('completed', 'Post has been saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $post = Post::where('slug', $slug)->first();
        return view('posts.post', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(post $post)
    {
        $post = Post::findOrFail($post->slug);
        return view('edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, post $post)
    {
        $updateData = $request->validate([
            'title' => 'required|max:255',
            'body' => 'required',
            'slug' => 'required|max:255',
        ]);
        Post::whereId($post->slug)->update($updateData);
        return redirect('/posts')->with('completed', 'Post has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(post $post)
    {
        $post = Post::findOrFail($post->slug);
        $post->delete();

        return redirect('/posts')->with('completed', 'Post has been deleted');
    }
}

resources/views/posts/create.blade.php
<x-layout>
    <section class="px-6 py-8">
        <main class="max-w-6xl mx-auto mt-10 lg:mt-20 space-y-6">
            <article class="max-w-4xl mx-auto lg:grid lg:grid-cols-12 gap-x-10">
                <div class="col-span-12 lg:text-center lg:pt-14 mb-10">
                    <div class="hidden lg:flex justify-between mb-6">
                        <a href="/"
                            class="mt-4 transition-colors duration-300 relative inline-flex items-center text-lg hover:text-blue-500">
                            <svg width="22" height="22" viewBox="0 0 22 22" class="mr-2">
                                <g fill="none" fill-rule="evenodd">
                                    <path stroke="#000" stroke-opacity=".012" stroke-width=".5" d="M21 1v20.16H.84V1z">
                                    </path>
                                    <path class="fill-current"
                                        d="M13.854 7.224l-3.847 3.856 3.847 3.856-1.184 1.184-5.04-5.04 5.04-5.04z">
                                    </path>
                                </g>
                            </svg> Back to Posts
                        </a>
                    </div>
                    <div class="border rounded mt-5 pl-4 pr-4 pt-4 pb-4">
                        <h1 class="mb-2 font-bold text-2xl lg:text-3xl">Create a New Post</h1>
                        <p class="mb-5 block text-gray-400 text-xs">Fill and submit this form to create a post</p>

                        <hr>
                        <div>
                            <form action="{{route('posts.store')}}" method="POST">
                                @csrf
                                <input type="hidden" name="user_id" value="1">
                                <div class="row">
                                    <div class="control-group col-12">
                                        <label for="title">
                                            <h5 class="font-bold">Post Title</h5>
                                        </label>
                                        <input type="text" id="title" class="form-control" name="title"
                                            placeholder="Enter Post Title" required>
                                    </div>

                                    <div class="control-group col-12">
                                        <label for="slug">
                                            <h5 class="font-bold">Post Slug</h5>
                                        </label>
                                        <input type="text" id="slug" class="form-control" name="slug"
                                            placeholder="Enter Post Slug" required>
                                    </div>

                                    <div class="control-group col-12">
                                        <label for="category">
                                            <h5 class="font-bold">Category</h5>
                                        </label>
                                        <select id="category" class="form-control" name="category_id"
                                            placeholder="Pick A Post Category" required>
                                            @foreach($categories as $category)
                                            <option value="{{$category->id}}"> 
                                            {{$category->name}}
                                            </option>
                                            @endforeach

                                        </select>
                                    </div>

                                    <div class="control-group col-12 mt-2">
                                        <label for="body">
                                            <h5 class="font-bold">Post Body</h5>
                                        </label>
                                        <textarea id="body" class="form-control" name="body"
                                            placeholder="Enter Post Body" rows="" required></textarea>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <div class="control-group col-12 text-center">
                                            <button type="submit"
                                                class="bg-green-500 ml-3 rounded-full text-xs font-semibold text-white uppercase py-3 px-5">Create
                                                Post</button>
                                      
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
        </main>
    </section>
</x-layout>

resources/views/posts/edit.blade.php
<x-layout>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12 pt-2">
                    <a href="/blog" class="btn btn-outline-primary btn-sm">Go back</a>
                    <div class="border rounded mt-5 pl-4 pr-4 pt-4 pb-4">
                        <h1 class="display-4">Edit Post</h1>
                        <p>Edit and submit this form to update a post</p>

                        <hr>

                        <form action="" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="control-group col-12">
                                    <label for="title">Post Title</label>
                                    <input type="text" id="title" class="form-control" name="title"
                                        placeholder="Enter Post Title" value="{{ $post->title }}" required>
                                </div>
                                <div class="control-group col-12 mt-2">
                                    <label for="body">Post Body</label>
                                    <textarea id="body" class="form-control" name="body" placeholder="Enter Post Body"
                                        rows="5" required>{{ $post->body }}</textarea>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="control-group col-12 text-center">
                                    <button id="btn-submit" class="btn btn-primary">
                                        Update Post
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </section>
</x-layout>

resources/views/posts/index.blade.php
<x-layout>

    @include ('posts.page_parts._posts-header')

    <main class="max-w-6xl mx-auto mt-6 lg:mt-20 space-y-6">
        @if ($posts->count())

        <x-posts-grid :posts="$posts" />

        @else

        <p class=" text-center">No posts yet. Please have some friggin patience!</p>

        @endif

    </main>
</x-layout>

resources/views/posts/page_parts/_posts-header.blade.php
<header class="max-w-xl mx-auto mt-20 text-center">
    <h1 class="text-4xl">
        Latest <span class="text-blue-500">Laravel From Scratch</span> News
    </h1>

    <div class="space-y-2 lg:space-y-0 lg:space-x-4 mt-4">
        <!--  Category -->
        <div class="relative lg:inline-flex bg-gray-100 rounded-xl">

            <x-dropdown>
                <x-slot name="trigger">
                    <button class="py-2 pl-3 pr-9 text-sm font-semibold w-full lg:w-32 text-left lg:inline-flex">

                        {{ isset($currentCategory) ? ucwords($currentCategory->name) : 'Categories'}}

                        <x-icon name="down-arrow" class="absolute pointer-events-none" style="right: 12px;" />
                    </button>
                </x-slot>
                <x-dropdown-item href='/' :active="request()->routeIs('home')">All</x-dropdown-item>

                @foreach($categories as $category)
                <x-dropdown-item href="/categories/{{$category->slug}}"
                    :active='request()->is("categories/{$category->slug}")'>{{ucwords($category->name)}}
                </x-dropdown-item>
                @endforeach
            </x-dropdown>

        </div>


        <!-- Search -->
        <div class="relative flex lg:inline-flex items-center bg-gray-100 rounded-xl px-3 py-2">
            <form method="GET" action="#"
                class="block text-left px-3 text-sm leading-6 hover:bg-blue-500 focus:bg-blue-500 focus:text-white hover:text-white">
                <input type="text" name="search" placeholder="Find something"
                    class="bg-transparent placeholder-black font-semibold text-sm">
            </form>
        </div>
    </div>
</header>

resources/views/posts/post.blade.php
<x-layout>
    <section class="px-6 py-8">
        <main class="max-w-6xl mx-auto mt-10 lg:mt-20 space-y-6">
            <article class="max-w-4xl mx-auto lg:grid lg:grid-cols-12 gap-x-10">
                <div class="col-span-4 lg:text-center lg:pt-14 mb-10">
                    <img src="/images/illustration-1.png" alt="" class="rounded-xl">

                    <p class="mt-4 block text-gray-400 text-xs">
                        Published <time>{{$post->created_at->diffForHumans()}}</time>
                    </p>

                    <div class="flex items-center lg:justify-center text-sm mt-4">
                        <img src="/images/lary-avatar.svg" alt="Lary avatar">
                        <div class="ml-3 text-left">
                            <h5 class="font-bold">
                                <a href='/authors/{{$post->author->username}}'>{{ $post->author->name}}</a></h5>
                        </div>
                    </div>
                    <div class="mt-4 inset-y-0 right-0">
                        <div class="">
                            <form id=" edit" class="" action="" method="GET">
                                @method('GET') @csrf
                                <button
                                    class="bg-yellow-500 ml-3 rounded-full text-xs font-semibold text-white uppercase py-3 px-5">Edit
                                    Post</button>
                            </form>
                        </div>
                    </div>
                    <div class="mt-4 inset-y-0 right-0">
                        <div class="">
                            <form id=" delete-frm" class="" action="" method="POST">
                                @method('DELETE') @csrf
                                <button
                                    class="bg-red-500 ml-3 rounded-full text-xs font-semibold text-white uppercase py-3 px-5">Delete
                                    Post</button>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-span-8">
                    <div class="hidden lg:flex justify-between mb-6">
                        <a href="/"
                            class="transition-colors duration-300 relative inline-flex items-center text-lg hover:text-blue-500">
                            <svg width="22" height="22" viewBox="0 0 22 22" class="mr-2">
                                <g fill="none" fill-rule="evenodd">
                                    <path stroke="#000" stroke-opacity=".012" stroke-width=".5" d="M21 1v20.16H.84V1z">
                                    </path>
                                    <path class="fill-current"
                                        d="M13.854 7.224l-3.847 3.856 3.847 3.856-1.184 1.184-5.04-5.04 5.04-5.04z">
                                    </path>
                                </g>
                            </svg> Back to Posts
                        </a>

                        <div class="space-x-2">
                            <x-category-button :category="$post->category" />
                        </div>
                    </div>

                    <h1 class="font-bold text-3xl lg:text-4xl mb-10">
                        {{$post->title}}
                    </h1>

                    <div class="space-y-4 lg:text-lg leading-loose">
                        <p>{!!$post->body!!}</p>
                    </div>
                </div>

                {{--
                <div class="col-span-4">
                    <div class="space-x-2">
                        <form id="delete-frm" class="" action="" method="POST">
                            @method('DELETE') @csrf
                            <button class="bg-red-500 ml-3 rounded-full text-xs font-semibold text-white uppercase py-3 px-5">Delete
                                Post</button>
                        </form>
                    </div>
                </div> --}}
            </article>
        </main>
    </section>
</x-layout>